/*----------------------------------------------------
MASV: N17DCAT031
HO TEN: VÕ PHI HÙNG
LAB: 04
NGAY: 24/09/2020
----------------------------------------------------*/
CREATE DATABASE QLSV
GO
USE QLSV
GO
CREATE TABLE SINHVIEN(
	MASV NVARCHAR(20) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME NULL,
	DIACHI NVARCHAR(200) NULL,
	MALOP VARCHAR(20) NULL,
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY (256) NOT NULL
);
CREATE TABLE NHANVIEN(
	MANV VARCHAR(20) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20) NULL,
	LUONG VARBINARY (256) NULL,
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY (256) NOT NULL
);
CREATE TABLE LOP(
	MALOP VARCHAR(20) PRIMARY KEY,
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR(20) NULL
);